config/routes.rb
Rails.application.routes.draw do
  root :to => "basic_unity_healths#index"
  
  resources :basic_unity_healths do
    member do
     get :show  
    end
    
    collection do
      get :index
      #get '/issues/list_page' => 'issues#list_page', :as => :list_page
    end
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :basic_unity_healths, only: [:find_ubs], :path => "" do
        collection do
          get :find_ubs, :path => "find_ubs"
        end
      end
    end
  end
end

app/models/geocode.rb
class Geocode < ActiveRecord::Base
  belongs_to :unity_basic_health
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :unity_basic_health
  
  def self.score_ranking(row)
    case row
      when "Desempenho muito acima da média"
        3
      when "Desempenho acima da média"
        2
      when "Desempenho mediano ou  um pouco abaixo da média"
        1
    end
  end
end

app/models/unity_basic_health.rb
class UnityBasicHealth < ActiveRecord::Base
  has_one :score
  has_one :geocode
  
  scope :by_geocode, -> (lat, long){ 
    Geocode
    .where("lat LIKE ? AND long LIKE ?", "%#{lat}%", "%#{long}%")
    .map(&:unity_basic_health)
  }
  
  scope :by_query, -> (query){ 
    where(
      "name LIKE ? 
      OR city LIKE ? 
      OR address LIKE ?
      OR neighborhood LIKE ?",
      "%#{query}%",
      "%#{query}%",
      "%#{query}%",
      "%#{query}%"
    )
  }

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

end

app/controllers/api/v1/basic_unity_healths_controller.rb
class Api::V1::BasicUnityHealthsController < Api::V1::BaseController
  require 'will_paginate/array'
  
  def find_ubs
    if params[:query].nil?
      render status: 500, json: {message: "Request out of params"}
    else
      query_params = params[:query].split(",")
      lat = query_params[0].to_i
      long = query_params[1].to_i
      
      ubs = UnityBasicHealth.by_geocode(lat, long)
      
      @ubs_entries = ubs.count 
      @ubs = ubs.sort_by { |u| u[:city] }
        .paginate(:page => params[:page], :per_page => 10)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basic_unity_healths_controller.rb
class BasicUnityHealthsController < ApplicationController
  has_scope :by_query

  def index
    if params["by_query"].present?
      @ubs = apply_scopes(UnityBasicHealth)
        .all.map{
          |m| [m.name.to_s, m.geocode.lat, m.geocode.long] 
        }

      @fix_marker =  @ubs.last.drop(1)
    else
      @ubs = []
      @fix_marker = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/basic_unity_healths/index.html.erb
<div>
  <div>
    <div class="col s12 m6">
      <div class="card #212121 grey darken-4 card-style">
        <div class="card-action">
          <%= simple_form_for basic_unity_healths_path, :method => 'get' do |f| %>
            <%= f.input :by_query,
              label: false, 
              input_html: { name: 'by_query', class: 'text-color' } %>
            <%= f.button :submit, "Buscar" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row row-dimension">
    <div id="map" class="map-size"></div>
  </div>
</div>

<div>
  <div id="ubs" value="<%= @ubs %>"></div>
  <div id="lat" value="<%= @fix_marker.first %>"></div>
  <div id="long" value="<%= @fix_marker.second %>"></div>
<div>
<%= javascript_include_tag "draw_maps" %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=raw Rails.application.secrets.google_maps_key%>&callback=myMap"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="cyan lighten-3" role="navigation">
  <div class="nav-wrapper container"><a id="logo-container" class="brand-logo"></a>
    <ul class="right hide-on-med-and-down">
      <li>
        <a>
          Brasil S A 
        </a>
      </li>
    </ul>
     
    <i data-activates="nav-mobile" class="button-collapse">
      <a href="/" class="material-icons icon-position">home</a>
    </i>
  </div>
</nav>

<div class="section no-pad-bot" id="index-banner">

</div>  

<%= yield %>

</body>
</html>